channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - snakemake-minimal==5.31.1 # updated from 5.7.1 because of envvars
  - mlst-cge==2.0.9
  - kma==1.4.9
  - git
  - pip
  - pip:
    - pytest
    - pytest-cov
    - pytest-profiling
    - coverage
    - pyyaml
    - argh
    - watchdog
    - bifrostlib
    - -e .