channels:
  - default
  - bioconda
  - conda-forge
dependencies:
  - snakemake-minimal==5.7.1
  - biopython==1.81 # moved from pip
  - pip
  - pip:
    - pytest
    - pytest-cov
    - pytest-profiling
    - coverage
    - pyyaml
    - argh
    - watchdog
    - bifrostlib
    - cgecore==1.5.6
    - tabulate==0.8.9
    - gitpython==3.1.14
    - python-dateutil==2.8.1
#   - biopython==1.81
    - -e .